import Opt from "../../../assets/images/opt-whats-new.webp";
import TheOneWhatsNew from "../../../assets/images/theone-whats-new.webp";
import RoyalVelvet from "../../../assets/images/royal velvet.webp";
import TenderCare from "../../../assets/images/tender care.webp";
import MilkandHoney from "../../../assets/images/milk and honey gold.webp";
import Possess from "../../../assets/images/possess.webp";
import LipBalm from "../../../assets/images/lip balm.webp";
import FacialOil from "../../../assets/images/facial oil.webp";
import AmberElixer from "../../../assets/images/amber elixer.webp";
import WellosphyRed from "../../../assets/images/wellosphy red.webp";
import WellosphyGreen from "../../../assets/images/willosphy green.webp";

export const products = [
  {
    id: 1,
    image: Opt,
    alt: "opt",
    isNew: true,
    stars: 4,
    category: "OPTIMALS",
    title: "Opt Optimals Daily Glow Multi-Protector SPF50",
    price: 12.99,
    originalPrice: 20.0,
  },
  {
    id: 2,
    image: Opt,
    alt: "opt",
    isNew: true,
    stars: 0,
    category: "OPTIMALS",
    title: "Opt Optimals Daily Glow Multi-Protector SPF50",
    price: 12.99,
    originalPrice: 20.0,
  },
   {
    id: 3,
    image: TheOneWhatsNew,
    alt: "opt",
    isNew: true,
    stars: 4,
    category: "THE ONES",
    title: "5 in 1 Wonder Lash Prom Queen Mascara - Black",
    price: 12.99,
    originalPrice: 20.0,
  },
   {
    id: 4,
    image: MilkandHoney,
    alt: "opt",
    isNew: false,
    stars: 0,
    category: "MILKANDHONEY",
    title: "MilkandHoney",
    price: 12.99,
    originalPrice: 17.0,
  },
   {
    id: 5,
    image: TenderCare,
    alt: "opt",
    isNew: true,
    stars: 5,
    category: "TENDERCARE",
    title: "Sweet Mandarin Multi-purpose Balm",
    price: 12.99,
    originalPrice: 17.0,
  },
   {
    id: 6,
    image: RoyalVelvet,
    alt: "opt",
    isNew: false,
    stars: 5,
    category: "THE ONES",
    title: "5 in 1 Wonder Lash Prom Queen Mascara - Black",
    price: 12.99,
    originalPrice: 17.0,
  },
   {
    id: 7,
    image: Possess,
    alt: "opt",
    isNew: false,
    stars: 5,
    category: "possess",
    title: "Absolute Eau de Parfum",
    price: 27.99,
    originalPrice: 47.0,
  },
   {
    id: 8,
    image: LipBalm,
    alt: "lip balm",
    isNew: false,
    stars: 4,
    category: "TENDER CARE ",
    title: "Natural Multi-purpose Balm",
    price: 3.49,
    originalPrice: 8.5,
  },
   {
    id: 9,
    image: FacialOil,
    alt: "Facial oil",
    isNew: false,
    stars: 5,
    category: "NOVAGE +",
    title: "Intense Nourishment Facial Oil Capsules",
    price: 24.99,
    originalPrice: 50.0,
  },
   {
    id: 10,
    image: AmberElixer,
    alt: "Amber Elixer",
    isNew: false,
    stars: 3,
    category: "AMBER ELIXER",
    title: "Eau de Parfum",
    price: 6.99,
    originalPrice: 13.0,
  },
   {
    id: 11,
    image: WellosphyGreen,
    alt: "WellsphyGreen",
    isNew: false,
    stars: 3,
    category: "WELLOSPHY",
    title: "Prebiotic Fibre Drink",
    price: 24.99,
    originalPrice: 50.0,
  },
   {
    id: 12,
    image: WellosphyRed,
    alt: "wellosphyRed",
    isNew: false,
    stars: 4,
    category: "WELLOSPHY",
    title: "Astaxanthin & Bilberry Extract",
    price: 24.99,
    originalPrice: 50.0,
  },
];
